### ISSUE TITLE
[FEATURE REQUEST] Outer borders with rounded corners

### ISSUE THREAD

**Issue by DutchPete** [jmouka/flexdown-obsidian-plugin#2]
Is it possible to add this as an option, e.g. %% border-rounded: yes.

**Comment by jmouka** [comment]
You can customize this yourself. See https://help.obsidian.md/Extending+Obsidian/CSS+snippets about custom styles. To make rounded borders, create a new snippet (eg my-flexdown.css) and paste this css:

```css
.flexdown-border {
	border-radius: 10px;
	overflow: hidden;
}
```

I'll also add it to possible updates.
